### ISSUE TITLE
[Question]: Need help on dapr retries.

### ISSUE THREAD

**Issue by Amit-limbasiya** [vishipayyallore/speaker-series-2024#46]
I want to draw your attention on the existing github issue: [7698](https://github.com/dapr/dapr/issues/7698)
I have seen your dapr side-car service to service invocation video on [youtube](https://www.youtube.com/watch?v=0YhKUkLHWgM). Really great explanation and great flow of the lecture👍. 

I want to know the content of component folders, and dapr-config,yaml files.
Or basically, I want to know that I have written the resiliency.yaml file as shown below:
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
scopes:
  - order-service
  - order-validation-service
spec:
  policies:
    timeouts:
    - general: 8s

    retries:
    - important:
        policy: exponential
        duration: 5s
        maxRetries: 10

    circuitBreakers:
    - simpleCB:
        maxRequests: 1
        interval: 60s
        timeout: 8s 
        trip: consecutiveFailures > 3

  targets:
    apps:
    - order-service:
        timeout: general
        retry: important
        circuitBreaker: simpleCB
    - order-validation-service:
        timeout: general
        retry: important
        circuitBreaker: simpleCB
```
Where the order-service(written in dotnet) will communicate with the order-validation-service(node API, same as your item-service). I want to apply the retry policy to the dotnet api, which in turn at the end communicate with node api, if the node API is down then dotnet API should retry. And Want to show the logs for the same as you have shown in your youtube lecture.

I doubt, I am missing dapr-config.yaml file or I might be wrong with side car invocation. Is it compulsory call order-service with the dapr port, or we can simply call it with the normal port of dotnet api which is assigned by dotnet in launchsettings. Just to inform: I have made the order-validation-service(Node API) down to test the retry policy.
